"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Clock3, ExternalLink, Languages, Mail, ShieldCheck, Smartphone, X } from "lucide-react";
import "./booking-bridge.css";

type Lang = "en" | "ja";
type Copy = { en: string; ja: string };
const c = (en: string, ja: string): Copy => ({ en, ja });
const included = [c("Floating ‘Book in English’ button for your existing website", "既存サイトに追加する「英語で予約」ボタン"), c("Bilingual booking panel with up to six services", "最大6メニュー対応の日英予約パネル"), c("Preferred date and time request step", "希望日時のリクエスト画面"), c("Handoff to LINE, Hot Pepper, your app or current form", "LINE・ホットペッパー・アプリ・既存フォームへの連携"), c("First-visit notes, hours, access and useful FAQs", "初回来店の案内・営業時間・アクセス・FAQ"), c("Installation guidance, one revision and launch support", "導入ガイド・1回の修正・公開サポート")];
const excluded = [c("A second calendar or reservation engine", "別のカレンダーや予約エンジン"), c("Customer database or automatic payments", "顧客データベースや自動決済"), c("Logo redesign, photography or a full rebuild", "ロゴ・撮影・サイト全体の作り直し"), c("Certified professional translation", "認証付きの専門翻訳"), c("Ongoing maintenance unless agreed separately", "別途合意のない継続保守")];
const inputs = [c("Official salon name and logo", "正式なサロン名とロゴ"), c("Four to six main services", "4〜6個の主なメニュー"), c("Starting prices and durations", "料金と所要時間"), c("Current booking links", "現在の予約リンク"), c("Opening hours and access", "営業時間とアクセス"), c("Approved salon photographs", "使用許可済みの写真"), c("First-visit and cancellation notes", "初回来店・キャンセル案内"), c("Japanese text approval contact", "日本語テキストの確認担当者")];

function Visual({ mobile, lang }: { mobile?: boolean; lang: Lang }) { return <figure className={mobile ? "bridge-campaign-visual bridge-campaign-visual--mobile" : "bridge-campaign-visual"}><Image src="/concepts/booking-bridge-campaign-v1.png" alt={lang === "en" ? "Bilingual salon booking screens" : "日英対応のサロン予約画面"} fill priority sizes={mobile ? "100vw" : "42vw"} /><figcaption><span>{lang === "en" ? "THE PRODUCT, AT A GLANCE" : "プロダクト概要"}</span><strong>{lang === "en" ? "Menu clarity → first-visit confidence → your existing booking channel" : "メニューを明確に → 初回来店の安心感 → 既存の予約方法へ"}</strong><small>{lang === "en" ? "Concept presentation · final design uses your approved brand and content" : "コンセプト提案・完成版は承認済みのブランドと情報で制作"}</small></figcaption></figure>; }

export default function BookingBridgePage() {
  const [lang, setLang] = useState<Lang>("en");
  const t = (x: Copy) => x[lang];
  useEffect(() => { const items = document.querySelectorAll<HTMLElement>(".bridge > section, .bridge .bridge-section-heading, .bridge .bridge-integration__visual, .bridge .bridge-integration__options > article, .bridge .bridge-screen-grid > article, .bridge .bridge-scope__lists > article, .bridge .bridge-process li, .bridge .bridge-inputs > *, .bridge .bridge-commercial > *"); items.forEach((item, i) => { item.dataset.reveal = ""; item.style.setProperty("--reveal-delay", `${(i % 4) * 70}ms`); }); const observer = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) { e.target.classList.add("is-visible"); observer.unobserve(e.target); } }), { threshold: .12, rootMargin: "0px 0px -8% 0px" }); items.forEach(item => observer.observe(item)); return () => observer.disconnect(); }, []);
  const ja = lang === "ja";
  const toggle = () => setLang(ja ? "en" : "ja");
  return <main className="bridge" lang={lang}>
    <div className="bridge-note"><span>{ja ? "個人サロン向け" : "FOR INDEPENDENT SALONS"}</span><span>日本のサロン向け</span><span>Booking Bridge · Kettles Studio</span></div>
    <header className="bridge-header"><Link href="/" className="bridge-wordmark" aria-label={ja ? "Kettles Studio ホーム" : "Kettles Studio home"}>KETTLES<span>.</span></Link><nav aria-label="Booking Bridge navigation"><a href="#integration">{ja ? "連携" : "Integration"}</a><a href="#how">{ja ? "ゲスト体験" : "Guest journey"}</a><a href="#scope">{ja ? "制作範囲" : "Scope"}</a><a href="#start">{ja ? "開始" : "Start"}</a></nav><div className="bridge-header__actions"><button type="button" className="bridge-language-switch" onClick={toggle} aria-label={ja ? "Switch to English" : "日本語に切り替える"}><Languages size={14} />{ja ? "English" : "日本語"}</button><Link className="bridge-demo-link" href="/nagi">{ja ? "サロンデモを見る" : "Open salon demo"}<ExternalLink size={14} /></Link></div></header>
    <section className="bridge-hero"><div className="bridge-hero__copy"><p className="bridge-kicker">{ja ? "Booking Bridge Kit · 日英対応の予約ガイド" : "Booking Bridge Kit · Floating bilingual booking guide"}</p><h1>{ja ? <>サイトはそのまま。<em>予約への入口を、もっと分かりやすく。</em></> : <>Keep your website.<em>Add one clearer way to book.</em></>}</h1><p className="bridge-hero__jp">{ja ? "Keep your website. Add one clearer path for English-speaking guests." : "サイトはそのまま。英語予約への分かりやすい入口だけを追加します。"}</p><Visual mobile lang={lang} /><p className="bridge-hero__intro">{ja ? "ウェブサイトや予約システムを変えずに、メニュー・初回来店情報・次の予約ステップを分かりやすくするモバイル対応の日英ガイドです。" : "A mobile-first bilingual guide that makes services, first-visit details and the next booking step clear—without replacing your website or reservation system."}</p><div className="bridge-actions"><Link href="/nagi" className="bridge-button bridge-button--dark">{ja ? "30秒デモを見る" : "View the 30-second demo"}<ArrowRight size={16} /></Link><a href="#scope" className="bridge-text-link">{ja ? "¥45,000に含まれる内容" : "What ¥45,000 includes"}</a></div><div className="bridge-hero__facts"><span><strong>¥45,000</strong>{ja ? "定額キット" : "Fixed-price kit"}</span><span><strong>7–10 {ja ? "日" : "days"}</strong>{ja ? "導入準備期間" : "Installation-ready delivery"}</span><span><strong>50 / 50</strong>{ja ? "開始時・公開時" : "Start and launch"}</span></div></div><div className="bridge-hero__visual" aria-label={ja ? "Booking Bridge モバイル画面プレビュー" : "Booking Bridge mobile journey preview"}><Visual lang={lang} /></div></section>
    <section className="bridge-principles"><article><Smartphone /><strong>{ja ? "ひとつのフローティングボタン" : "One floating button"}</strong><span>{ja ? "今あるウェブサイトに追加します。" : "Added to the website you already have."}</span></article><article><Languages /><strong>{ja ? "ひとつの予約パネル" : "One guided booking panel"}</strong><span>{ja ? "メニュー・来店情報・希望日時を日英で案内。" : "Services, visit details and preferred time in Japanese + English."}</span></article><article><ShieldCheck /><strong>{ja ? "既存システムへ連携" : "One existing-system handoff"}</strong><span>{ja ? "LINE・ホットペッパー・アプリ・フォームへ。" : "LINE, Hot Pepper, app or form—no duplicate calendar."}</span></article></section>
    <section className="bridge-integration" id="integration"><div className="bridge-section-heading"><p className="bridge-kicker">{ja ? "既存ウェブサイトへの追加方法" : "HOW IT JOINS YOUR CURRENT WEBSITE"}</p><h2>{ja ? "ボタンひとつ、ガイドひとつ、連携ひとつ。" : "One button, one guide, one handoff."}</h2><p>{ja ? "興味を持ったゲストを、チームが使い慣れた予約システムへつなぐ日英の導線です。" : "Booking Bridge adds a bilingual path between a curious guest and the system your team already checks."}</p></div><div className="bridge-integration__visual"><article className="bridge-existing-site"><div className="bridge-window-bar"><i /><i /><i /><span>your-salon.jp</span></div><div className="bridge-site-nav"><strong>SALON</strong><span>Menu</span><span>Style</span><span>Access</span></div><div className="bridge-site-hero"><small>{ja ? "現在のウェブサイト" : "YOUR CURRENT WEBSITE"}</small><strong>{ja ? "リニューアル不要。" : "No redesign required."}</strong><p>{ja ? "写真・ページ・ドメイン・日本語の導線はそのままです。" : "Your photos, pages, domain and Japanese customer journey remain in place."}</p><button>{ja ? "英語で予約" : "Book in English"}<ArrowRight size={13} /></button></div><span className="bridge-change-label">{ja ? "追加するのはこのボタンだけ" : "Only this button is added"}</span></article><div className="bridge-flow-arrow" aria-hidden="true"><ArrowRight /></div><article className="bridge-bridge-preview"><div className="bridge-preview-top"><span>BOOKING BRIDGE</span><small>EN / JP</small></div><strong>{ja ? "初めてのゲストに必要な情報を。" : "Everything a first-time guest needs."}</strong><ul><li><Check size={12} />{ja ? "メニューと料金" : "Services and starting prices"}</li><li><Check size={12} />{ja ? "初回来店の案内" : "First-visit guidance"}</li><li><Check size={12} />{ja ? "言語とアクセス情報" : "Language and access notes"}</li></ul><div className="bridge-preview-actions"><span>LINE</span><span>Hot Pepper</span><span>{ja ? "サロンフォーム" : "Salon form"}</span></div></article></div><div className="bridge-keeps"><span>{ja ? "サイトはそのまま" : "Your website stays"}</span><span>{ja ? "ドメインはそのまま" : "Your domain stays"}</span><span>{ja ? "カレンダーはそのまま" : "Your calendar stays"}</span><span>{ja ? "データはそのまま" : "Your data stays"}</span><strong>{ja ? "二重管理は不要。" : "No duplicate reservation management."}</strong></div></section>
    <section className="bridge-journey" id="how"><div className="bridge-section-heading"><p className="bridge-kicker">{ja ? "3画面で伝える予約体験" : "THE THREE-SCREEN STORY"}</p><h2>{ja ? "理解する。安心する。予約へ進む。" : "Understand. Feel ready. Continue."}</h2><p>{ja ? "3つの情報で、サロンを見つけてから予約するまでの迷いを減らします。" : "Three decisions remove the hesitation between finding the salon and requesting a visit."}</p></div><div className="bridge-screen-grid">{[c("Understand the offer", "メニューを理解する"), c("Feel safe enough to act", "安心して進む"), c("Use the existing system", "いつもの予約方法へ")].map((x, i) => <article key={i}><span>0{i + 1}</span><div className={`bridge-screen-card bridge-screen-card--${i === 0 ? "menu" : i === 1 ? "trust" : "handoff"}`}><small>{i === 2 ? "CONTINUE WITH" : "EN / JP"}</small><strong>{i === 0 ? (ja ? "メニューと料金" : "Services and starting prices") : i === 1 ? (ja ? "初回来店" : "Your first visit") : "LINE · HOT PEPPER"}</strong>{i === 1 && <small>{ja ? "持ち物・流れ・確認事項" : "What to bring · what happens · what is confirmed"}</small>}</div><h3>{t(x)}</h3><p>{t([c("Services, prices and language support become clear before the customer contacts the salon.", "連絡前にメニュー・料金・言語対応が明確になります。"), c("First-visit guidance answers the quiet questions that often stop a booking.", "初回来店の案内が、予約前の小さな不安に答えます。"), c("The final action opens the booking channel the salon already knows.", "最後はサロンが使い慣れた予約方法へ進みます。")][i])}</p></article>)}</div></section>
    <section className="bridge-scope" id="scope"><div className="bridge-scope__intro"><p className="bridge-kicker">{ja ? "明確な制作範囲 · FIXED SCOPE" : "FIXED SCOPE · 明確な制作範囲"}</p><h2>{ja ? "サイト制作ではなく、導入できる予約キット。" : "A focused installable kit—not a website project."}</h2><p>{ja ? "既存のサイト・ブランド・予約システム・カレンダー・顧客データはそのままです。" : "Your existing website, branding, booking system, calendar and customer data remain in place."}</p></div><div className="bridge-scope__lists"><article><span className="bridge-list-label bridge-list-label--yes">{ja ? "含まれるもの" : "Included"}</span><ul>{included.map(x => <li key={x.en}><Check size={14} />{t(x)}</li>)}</ul></article><article><span className="bridge-list-label">{ja ? "含まれないもの" : "Not included"}</span><ul>{excluded.map(x => <li key={x.en}><X size={14} />{t(x)}</li>)}</ul></article></div></section>
    <section className="bridge-process"><div className="bridge-section-heading"><p className="bridge-kicker">{ja ? "シンプルな納品" : "SIMPLE DELIVERY"}</p><h2>{ja ? "承認から公開まで4ステップ。" : "Four steps from yes to launch."}</h2></div><ol>{[c("Confirm", "確認"), c("Collect", "情報収集"), c("Build", "制作"), c("Connect", "連携")].map((x, i) => <li key={i}><span>0{i + 1}</span><strong>{t(x)}</strong><p>{t([c("We confirm the current booking route and launch goal.", "現在の予約導線と公開目標を確認します。"), c("The salon provides approved information, links and photographs.", "承認済みの情報・リンク・写真をご提供いただきます。"), c("Kettles prepares the bilingual mobile page and review version.", "Kettlesが日英モバイルページと確認版を制作します。"), c("Approved buttons open the salon’s existing booking channels.", "承認されたボタンから既存の予約方法へつなぎます。")][i])}</p></li>)}</ol></section>
    <section className="bridge-inputs"><div><p className="bridge-kicker">{ja ? "サロンからいただく情報" : "WHAT WE NEED FROM THE SALON"}</p><h2>{ja ? "チェックリストひとつ。長い打合せ不要。" : "One checklist. No long meetings."}</h2><p>{ja ? "下記の情報と初回のお支払いが揃い次第、制作を開始します。" : "Production begins after the information below is complete and the first payment is received."}</p></div><ul>{inputs.map(x => <li key={x.en}><Check size={15} />{t(x)}</li>)}</ul></section>
    <section className="bridge-commercial" id="start"><div className="bridge-commercial__price"><p className="bridge-kicker">BOOKING BRIDGE</p><span>{ja ? "制作費" : "Project fee"}</span><strong>¥45,000</strong><small>{ja ? "税金が発生する場合は開始前にご案内します。" : "Any applicable tax is confirmed before work begins."}</small></div><div className="bridge-commercial__copy"><h2>{ja ? "サイトの作り直しではなく、Booking Bridge Kitを。" : "Buy the Booking Bridge Kit—not a website redesign."}</h2><ul><li><Clock3 size={15} />{ja ? "素材受領後7〜10営業日" : "7–10 working days after all materials arrive"}</li><li><ShieldCheck size={15} />{ja ? "開始時50%・公開前50%" : "50% to begin · 50% before public launch"}</li><li><Check size={15} />{ja ? "1回の修正を含む" : "One revision included"}</li></ul><a className="bridge-button bridge-button--orange" href="mailto:norman@kettles.studio?subject=Booking%20Bridge%20discussion"><Mail size={16} />{ja ? "Booking Bridgeについて相談" : "Discuss the Booking Bridge Kit"}</a><p className="bridge-commercial__jp">{ja ? "現在の予約方法を確認し、最初に改善できる導線をご提案します。" : "We review your current booking flow and suggest the clearest first improvement."}</p></div></section>
    <footer className="bridge-footer"><div><strong>KETTLES.</strong><span>{ja ? "役立つ仕組みを、丁寧に。" : "Useful systems, thoughtfully presented."}</span></div><div><Link href="/nagi">{ja ? "サロンデモ" : "Salon demonstration"}</Link><Link href="/founder">{ja ? "Normanについて" : "About Norman"}</Link><a href="mailto:norman@kettles.studio">norman@kettles.studio</a></div></footer>
  </main>;
}
